### ISSUE TITLE
Problem in running using github actions

### ISSUE THREAD

**Issue by RomaTk** [ffbinaries/ffbinaries-node#38]
Here the error which I get:

Error: ENOENT: no such file or directory, rename '/home/runner/.ffbinaries-cache/ffmpeg-4.4.1-linux-64.zip.part' -> '/home/runner/.ffbinaries-cache/ffmpeg-4.4.1-linux-64.zip'
    at Object.renameSync (node:fs:1030:3)
    at Request._callback (/home/runner/work/minigames/minigames/node_modules/ffbinaries/ffbinaries-lib.js:287:15)
    at Request.self.callback (/home/runner/work/minigames/minigames/node_modules/request/request.js:1[85](https://github.com/SandsB2B/minigames/runs/8285622320?check_suite_focus=true#step:5:86):22)
    at Request.emit (node:events:513:28)
    at Request.emit (node:domain:552:15)
    at Request.<anonymous> (/home/runner/work/minigames/minigames/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:525:35)
    at Request.emit (node:domain:552:15)
    at IncomingMessage.<anonymous> (/home/runner/work/minigames/minigames/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)

**Comment by masterWeber** [comment]
I had the same problem on Windows

**Comment by RomaTk** [comment]
> I had the same problem on Windows

I haven`t problems with windows machines, but If I`ll get this case I`ll share solution if find it.

**Comment by vot** [comment]
Hi @RomaTk - thanks for raising the issue and apologies about the delay.

This appears to be thrown when renaming the downloaded file (we append the `.part` to the filename while the file is still incomplete, then remove it upon success).

Does this happen in a public repo?
If it's private could you create a public one or provide the workflow definition file to reproduce this?

Thanks in advance,
Vot

**Comment by vot** [comment]
> I had the same problem on Windows

@masterWeber if this is reproducible could you try it again with a newly published version 1.1.5?
It includes changes from Pull Request #37 that relate to Windows path concatenation, that might just resolve the problem you've been experiencing.
